### POST request to example server
POST https://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
  "name": "yyrr",
  "email": "hussain1g@dwd.com",
  "password": "password1",
  "passwordConfirm": "password1"
}

### post request to example server
POST https://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "email": "hussain1g@dwd.com",
  "password": "password1"
}

### get request to example server
GET https://localhost:5000/api/v1/users/me

### GET request to example server
GET https://localhost:5000/api/v1/auth/logout