### POST request to example server
POST https://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
  "fname": "sona2",
  "lname": "hussain",
  "username": "sona2_hussain",
  "email": "hussain@gmail.com",
  "password": "password1",
  "passwordConfirm": "password1"
}

### post request to example server
POST https://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "email": "hussain@gmail.com",
  "password": "password2"
}

### POST request to example server
POST https://localhost:5000/api/v1/auth/request-password-reset
Content-Type: application/json

{
  "email": "hussain@gmail.com"
}
### POST request to example server
POST https://localhost:5000/api/v1/auth/refresh-token

### POST request to example server
PUT https://localhost:5000/api/v1/auth/reset-password
Content-Type: application/json

{
  "token": "MTJiMjhkZTgtMmY1ZS00YmI3LWFkZmYtMzE4NjUxN2IwMGFi",
  "newPassword": "password2"
}

### get request to example server
GET https://localhost:5000/api/v1/users/me

### GET request to example server
GET https://localhost:5000/api/v1/auth/logout

### GET request to example server
GET https://localhost:5000/api/v1/auth/verify-email?code=VnDc18bgKIM4sKBFBFvc

