### POST request to example server
POST https://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
  "name": "sona2",
  "email": "hussain.sabt@gmail.com",
  "password": "password1",
  "passwordConfirm": "password1"
}

### post request to example server
POST https://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "email": "hussain.sabt@gmail.com",
  "password": "password2"
}

### POST request to example server
POST https://localhost:5000/api/v1/auth/request-password-reset
Content-Type: application/json

{
  "email": "hussain.sabt@gmail.com"
}

### POST request to example server
PUT https://localhost:5000/api/v1/auth/reset-password
Content-Type: application/json

{
  "token": "968abdec-3696-4dcd-93bb-3bb77c4bce69",
  "newPassword": "password2"
}

### get request to example server
GET https://localhost:5000/api/v1/users/me

### GET request to example server
GET https://localhost:5000/api/v1/auth/logout

### GET request to example server
GET https://localhost:5000/api/v1/auth/verify-email?code=KG309xHUbLyxOYzbcTQV

